# Generated by Django 4.2 on 2023-05-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_store_app', '0002_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
